In [1]:
import numpy as np

In [2]:
p = np.array([9,8,7])
q = np.array([3,2,4])

In [3]:
print(p)

[9 8 7]


In [4]:
print(q)

[3 2 4]


In [5]:
p + q

array([12, 10, 11])

In [6]:
p - q

array([6, 6, 3])

In [7]:
p * q

array([27, 16, 28])

In [8]:
p / q

array([3.  , 4.  , 1.75])

In [9]:
p * p + q * q

array([90, 68, 65])

In [10]:
p > q

array([ True,  True,  True])

In [11]:
p < q

array([False, False, False])

In [12]:
q.dot(p)

71

In [13]:
np.dot(p, q)

71

In [14]:
p * 4

array([36, 32, 28])

In [15]:
numbers = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]).reshape(2, 5)

In [16]:
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
numbers.sum()

55

In [18]:
numbers.min()

1

In [19]:
numbers.max()

10

In [20]:
print('Mean: ', numbers.mean())

Mean:  5.5


In [21]:
nums =np.arange(16).reshape(4, 4)

In [22]:
nums

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
nums.sum()

120

In [24]:
nums.sum(axis=1)

array([ 6, 22, 38, 54])