In [1]:
import numpy as np

In [2]:
x = np.arange(16)**3

In [3]:
x

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375], dtype=int32)

In [4]:
x[3]

27

In [5]:
x[1:8]

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [6]:
x[1:-8]

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [7]:
x[::-1]

array([3375, 2744, 2197, 1728, 1331, 1000,  729,  512,  343,  216,  125,
         64,   27,    8,    1,    0], dtype=int32)

In [8]:
data = np.array([['Google', 'Microsoft', 'Apple', 'Amazon', 'Flipkart'],
                [10000000, 200000000, 45000, 12321, 123434, 123456],
                [1234, 1234, 1234, 1234, 1234, 123456]])

<ipython-input-8-fa48ebc6d98c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data = np.array([['Google', 'Microsoft', 'Apple', 'Amazon', 'Flipkart'],


In [9]:
data

array([list(['Google', 'Microsoft', 'Apple', 'Amazon', 'Flipkart']),
       list([10000000, 200000000, 45000, 12321, 123434, 123456]),
       list([1234, 1234, 1234, 1234, 1234, 123456])], dtype=object)

In [10]:
data[0]

['Google', 'Microsoft', 'Apple', 'Amazon', 'Flipkart']

In [11]:
data[: 2]

array([list(['Google', 'Microsoft', 'Apple', 'Amazon', 'Flipkart']),
       list([10000000, 200000000, 45000, 12321, 123434, 123456])],
      dtype=object)

In [12]:
data[2:]

array([list([1234, 1234, 1234, 1234, 1234, 123456])], dtype=object)

In [13]:
data[-1:]

array([list([1234, 1234, 1234, 1234, 1234, 123456])], dtype=object)