In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
for i in x:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [5]:
array1 = np.arange(15).reshape(3, 5)

In [6]:
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
array1.flatten(order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [8]:
array2 = np.arange(16).reshape(4,4)

In [9]:
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
array2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
for i in np.nditer(array2, order='C', flags=['external_loop']):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
