In [1]:
import numpy as np

In [2]:
x = np.arange(8)

In [3]:
print(x)

[0 1 2 3 4 5 6 7]


In [4]:
y = np.arange(16).reshape(4, 4)

In [5]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
np.set_printoptions(threshold=50)
print(np.arange(100).reshape(10, 10))

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 ...
 [70 71 72 ... 77 78 79]
 [80 81 82 ... 87 88 89]
 [90 91 92 ... 97 98 99]]
