In [1]:
import numpy as np

In [2]:
circle_radii = np.array([145, 120, 90, 60, 45, 30])

In [3]:
circle_diameters = 2 * circle_radii

In [4]:
circle_diameters

array([290, 240, 180, 120,  90,  60])

In [5]:
circle_areas = np.pi * circle_radii**2

In [6]:
circle_areas

array([66051.98554173, 45238.93421169, 25446.90049408, 11309.73355292,
        6361.72512352,  2827.43338823])

In [7]:
angles_degrees = np.pi / 100

In [8]:
angles_degrees

0.031415926535897934

In [9]:
np.sin(angles_degrees)

0.03141075907812829

In [10]:
np.cos(angles_degrees)

0.9995065603657316

In [11]:
np.tan(angles_degrees)

0.03142626604335115

In [12]:
sine_values = np.sin(angles_degrees)

In [13]:
sine_values

0.03141075907812829

In [14]:
x = np.arange(6, 14, 5)

In [15]:
x

array([ 6, 11])

In [16]:
expo = np.exp(x)

In [17]:
expo

array([  403.42879349, 59874.1417152 ])

In [18]:
sqrt = np.sqrt(x)

In [19]:
sqrt

array([2.44948974, 3.31662479])

In [20]:
np.sqrt(x)

array([2.44948974, 3.31662479])

In [21]:
np.median(x)

8.5