In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data

Money Discussion  Argency  Spam
0                   77        3     1
1                   36       12     0
2                   18       24     0
3                   41       71     1
4                    2       56     1
...                ...      ...   ...
2052                93       30     0
2053                80       93     1
2054                 9       19     1
2055                42       85     0
2056                11        0     1

[2057 rows x 3 columns]

In [4]:
data.head()

Money Discussion  Argency  Spam
0                77        3     1
1                36       12     0
2                18       24     0
3                41       71     1
4                 2       56     1

In [5]:
data.tail()

Money Discussion  Argency  Spam
2052                93       30     0
2053                80       93     1
2054                 9       19     1
2055                42       85     0
2056                11        0     1

In [6]:
data.describe()

Money Discussion      Argency         Spam
count       2057.000000  2057.000000  2057.000000
mean          49.919300    50.650948     0.491979
std           29.131767    28.964232     0.500057
min            0.000000     0.000000     0.000000
25%           25.000000    26.000000     0.000000
50%           48.000000    51.000000     0.000000
75%           76.000000    76.000000     1.000000
max          100.000000   100.000000     1.000000

In [7]:
import numpy as np

In [8]:
def split_data(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indicies = shuffled[:test_set_size]
    train_indicies = shuffled[test_set_size:]
    return data.iloc[train_indicies], data.iloc[test_indicies]

In [9]:
train, test = split_data(data, 0.2)

In [10]:
train

Money Discussion  Argency  Spam
1366                62       83     1
67                   8       87     0
1001                26       84     1
567                 79        5     1
1271                47       14     1
...                ...      ...   ...
1638                63        1     0
1095                65       52     1
1130                99       13     1
1294                 7       90     0
860                 84       23     1

[1646 rows x 3 columns]

In [11]:
test

Money Discussion  Argency  Spam
184                 14       58     1
1947                33       41     1
251                 12       88     0
1121                34       86     1
1487                37       67     0
...                ...      ...   ...
322                 67       54     1
1232                18        7     1
266                 55       28     1
1170                54       54     0
1474                41        3     0

[411 rows x 3 columns]

In [12]:
X_train = train[['Money Discussion', 'Argency']].to_numpy()
X_test = test[['Money Discussion', 'Argency']].to_numpy()

In [13]:
X_train

array([[62, 83],
       [ 8, 87],
       [26, 84],
       ...,
       [99, 13],
       [ 7, 90],
       [84, 23]], dtype=int64)

In [14]:
X_test

array([[ 14,  58],
       [ 33,  41],
       [ 12,  88],
       [ 34,  86],
       [ 37,  67],
       [ 69,  96],
       [ 16,  56],
       [ 74,  71],
       [  1,  94],
       [ 77,  59],
       [ 15,  50],
       [ 68,  61],
       [ 59,   7],
       [ 16,   9],
       [ 40,  48],
       [ 95,  80],
       [ 71,  99],
       [ 59,  20],
       [ 78, 100],
       [ 50,  45],
       [ 75,  38],
       [ 34,  42],
       [ 41,  81],
       [ 25,  96],
       [ 32,  60],
       [ 90,  22],
       [ 83,  28],
       [ 85,  56],
       [ 68,  18],
       [ 99,  60],
       [ 11,  29],
       [ 92,  60],
       [ 23,  88],
       [  0,  81],
       [ 16,  84],
       [ 11,  82],
       [ 36,  87],
       [ 83,  96],
       [ 82,  22],
       [ 38,  55],
       [  9,  86],
       [ 70,  66],
       [ 65,  28],
       [ 95,  99],
       [ 37,  88],
       [ 96,  13],
       [ 38,  20],
       [ 70,  28],
       [ 74,  91],
       [ 50,  31],
       [ 35,  79],
       [ 59,  90],
       [ 96,

In [15]:
Y_train = train[['Spam']].to_numpy().reshape(1646, )
Y_test = test[['Spam']].to_numpy().reshape(411, )

In [16]:
Y_train

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [17]:
Y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

In [28]:
Features = [100, 89]
Label = clf.predict([Features])

In [29]:
Label[0]

1