In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv('data.csv')

In [3]:
housing.head()

Area  Hall  Bathroom  Bed room  Kitchen  Terrace   Price
0   680     1         2         2        1        1  130636
1   844     1         3         2        1        1   82400
2   894     1         2         3        1        2  109555
3   872     1         3         3        1        2   72404
4   968     1         2         2        1        2   88595

In [4]:
housing.tail()

Area  Hall  Bathroom  Bed room  Kitchen  Terrace   Price
1994   933     1         3         1        1        1  171889
1995   671     1         2         1        1        1  185501
1996   991     1         2         1        1        2  155173
1997   650     1         2         3        1        2  164954
1998   989     1         1         3        1        2  176972

In [5]:
housing.describe()

Area    Hall     Bathroom     Bed room  Kitchen      Terrace  \
count  1999.000000  1999.0  1999.000000  1999.000000   1999.0  1999.000000   
mean    797.654827     1.0     1.994997     2.036018      1.0     1.473737   
std     116.109553     0.0     0.820761     0.822423      0.0     0.499435   
min     600.000000     1.0     1.000000     1.000000      1.0     1.000000   
25%     699.000000     1.0     1.000000     1.000000      1.0     1.000000   
50%     795.000000     1.0     2.000000     2.000000      1.0     1.000000   
75%     894.000000     1.0     3.000000     3.000000      1.0     2.000000   
max    1000.000000     1.0     3.000000     3.000000      1.0     2.000000   

               Price  
count    1999.000000  
mean   105081.270135  
std     54594.909035  
min     10170.000000  
25%     58141.000000  
50%    105767.000000  
75%    151382.500000  
max    199974.000000

In [6]:
import numpy as np

In [7]:
def split_data(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indicies = shuffled[:test_set_size]
    train_indicies = shuffled[test_set_size:]
    return data.iloc[train_indicies], data.iloc[test_indicies]

In [8]:
train, test = split_data(housing, 0.2)

In [9]:
train

Area  Hall  Bathroom  Bed room  Kitchen  Terrace   Price
966    723     1         3         2        1        1   57623
240    990     1         1         2        1        1   72965
812    727     1         3         2        1        1  137595
1824   662     1         1         2        1        1   15635
1244   728     1         2         2        1        2   91993
...    ...   ...       ...       ...      ...      ...     ...
1130   702     1         3         3        1        1   42629
1294   971     1         1         3        1        1   60759
860    957     1         2         1        1        2   71732
1459   700     1         1         3        1        1   67869
1126   628     1         1         2        1        2   81480

[1600 rows x 7 columns]

In [10]:
test

Area  Hall  Bathroom  Bed room  Kitchen  Terrace   Price
256    865     1         1         1        1        2   44043
352    670     1         1         1        1        1   40023
298    700     1         1         1        1        1   50619
581    889     1         1         3        1        1   89023
1288   750     1         2         2        1        1   73466
...    ...   ...       ...       ...      ...      ...     ...
1616   681     1         2         2        1        2  164032
650    824     1         1         2        1        1   76591
1973   869     1         2         1        1        1   64083
261    748     1         2         2        1        2  109197
1305   733     1         1         2        1        2   34984

[399 rows x 7 columns]

In [11]:
X_train = train[['Area', 'Hall', 'Bathroom', 'Bed room', 'Kitchen', 'Terrace']].to_numpy()
X_test = test[['Area', 'Hall', 'Bathroom', 'Bed room', 'Kitchen', 'Terrace']].to_numpy()

In [12]:
X_train

array([[723,   1,   3,   2,   1,   1],
       [990,   1,   1,   2,   1,   1],
       [727,   1,   3,   2,   1,   1],
       ...,
       [957,   1,   2,   1,   1,   2],
       [700,   1,   1,   3,   1,   1],
       [628,   1,   1,   2,   1,   2]], dtype=int64)

In [13]:
X_test

array([[865,   1,   1,   1,   1,   2],
       [670,   1,   1,   1,   1,   1],
       [700,   1,   1,   1,   1,   1],
       ...,
       [869,   1,   2,   1,   1,   1],
       [748,   1,   2,   2,   1,   2],
       [733,   1,   1,   2,   1,   2]], dtype=int64)

In [14]:
Y_train = train[['Price']].to_numpy().reshape(1600 ,)
Y_test = test[['Price']].to_numpy().reshape(399 ,)

In [15]:
Y_train

array([ 57623,  72965, 137595, ...,  71732,  67869,  81480], dtype=int64)

In [16]:
Y_test

array([ 44043,  40023,  50619,  89023,  73466, 131909, 193167, 188294,
       140460, 155961,  91360, 164954, 180287, 164120,  57246,  74036,
       195751, 102620,  86074,  34709, 145115,  50637, 120771,  14576,
        60791, 135199,  56362, 113910,  58604,  94006,  38233,  70121,
       171780, 154929, 169947,  49261,  76418,  31060,  13004, 123603,
        54284, 102903,  27995,  57734,  34682, 101420, 115738, 105203,
       136366,  71288,  35214,  16822, 185800,  90954, 195381, 131739,
        89882,  64766, 131948,  96485,  29675, 137813, 167630, 186639,
       187985, 104580,  36887,  16942,  55221, 183534, 199300,  68154,
       193655, 107201,  82116,  39023, 195177, 143879, 184239,  76825,
       132826, 105858,  36941, 169510,  11027,  55618, 177266, 160625,
        97767,  26079, 121915,  28358, 111675,  20982, 105768, 152225,
       168904, 145022, 114288, 119358, 120732,  10780,  84873, 184309,
       188779,  26343, 124631, 183969,  49678,  31048, 197195,  49678,
      

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

c:\users\omprakash\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [19]:
inputFeatures = [1, 23456, 345, 1, 89, 1]
predicted = clf.predict([inputFeatures])

In [20]:
predicted[0]

68651